# Using postgres latest image
FROM postgres:11.1

MAINTAINER Ramakrishna Kothamasu "krishna.ubuntu@gmail.com"

# Using the environment variables instead of start-up-script
ENV POSTGRES_USER admin

# TODO(me) : Not a best ptractice to keep password in vcs, change later
ENV POSTGRES_PASSWORD password
ENV POSTGRES_DB tempdb
